---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
- apiGroups:
  - cdi.kubevirt.io
  resources:
  - datavolumes
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachines
  verbs:
  - create
  - get
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
- apiGroups:
  - vma.nutanix.io
  resources:
  - migrationplans
  - migrations
  - nutanixproviders
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vma.nutanix.io
  resources:
  - migrationplans/status
  - migrations/status
  - nutanixproviders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vma.nutanix.io
  resources:
  - migrations/finalizers
  - nutanixproviders/finalizers
  verbs:
  - update
- apiGroups:
  - vma.nutanix.io
  resources:
  - networkmaps
  - storagemaps
  verbs:
  - get
